# Default values for YOUR_PROJECT.
replicaCount: 1

nameOverride: ""
fullnameOverride: ""

# Namespace where the controller will be installed
namespace: YOUR_PROJECT-system

image:
  repository: YOUR_DOCKER_REGISTRY/YOUR_PROJECT
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

imagePullSecrets: []

serviceAccount:
  create: true
  name: "YOUR_PROJECT-controller-manager"
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
